version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build-and-lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint
workflows:
    build-and-test:
      jobs:
        - build-and-lint
